[package]
name = "vspreview-rs"
version = "0.1.2"
authors = ["quietvoid"]
edition = "2021"
rust-version = "1.70.0"
license = "GPL-3.0"

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.6", features = ["derive", "wrap_help", "deprecated"] }
eframe = { version = "0.23.0", features = ["persistence"] }
fast_image_resize = "2.7.3"
image = { version = "0.24.7", default-features = false, features = ["png"] }
rgb = "0.8.36"
itertools = "0.11.0"
lcms2 = "6.0.0"
num_enum = "0.7.0"
parking_lot = "0.12.1"
poll-promise = "0.3.0"
rfd = "0.12.0"
serde_derive = "1.0.188"
serde = "1.0.188"
vapoursynth = { version = "0.4.0", features = ["vapoursynth-api-36", "vapoursynth-functions", "vsscript-api-32", "vsscript-functions"] }

[[bin]]
name = "vspreview-rs"
path = "src/main.rs"

[profile.release]
opt-level = 3
strip = true
